package main

import (
	wpmodels "ednevnik-backend/models/workspace"
)

// CurriculumsSBK for static data
var CurriculumsSBK = []wpmodels.CurriculumCreate{
	// Bosanski NPP osnovne škole za kanton SBK
	{CurriculumCode: "bos_primary_1_sbk", CurriculumName: "Nastavni plan i program za I razred osnovne škole SBK - Bosanski jezik", ClassCode: "I", NPPCode: "BOS", CantonCode: "SBK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_2_sbk", CurriculumName: "Nastavni plan i program za II razred osnovne škole SBK - Bosanski jezik", ClassCode: "II", NPPCode: "BOS", CantonCode: "SBK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_3_sbk", CurriculumName: "Nastavni plan i program za III razred osnovne škole SBK - Bosanski jezik", ClassCode: "III", NPPCode: "BOS", CantonCode: "SBK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_4_sbk", CurriculumName: "Nastavni plan i program za IV razred osnovne škole SBK - Bosanski jezik", ClassCode: "IV", NPPCode: "BOS", CantonCode: "SBK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_5_sbk", CurriculumName: "Nastavni plan i program za V razred osnovne škole SBK - Bosanski jezik", ClassCode: "V", NPPCode: "BOS", CantonCode: "SBK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_6_sbk", CurriculumName: "Nastavni plan i program za VI razred osnovne škole SBK - Bosanski jezik", ClassCode: "VI", NPPCode: "BOS", CantonCode: "SBK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_7_sbk", CurriculumName: "Nastavni plan i program za VII razred osnovne škole SBK - Bosanski jezik", ClassCode: "VII", NPPCode: "BOS", CantonCode: "SBK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_8_sbk", CurriculumName: "Nastavni plan i program za VIII razred osnovne škole SBK - Bosanski jezik", ClassCode: "VIII", NPPCode: "BOS", CantonCode: "SBK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_9_sbk", CurriculumName: "Nastavni plan i program za IX razred osnovne škole SBK - Bosanski jezik", ClassCode: "IX", NPPCode: "BOS", CantonCode: "SBK", TenantType: "primary", FinalCurriculum: true},
}

// CurriculumSubjectsSBKPrimary for static data
var CurriculumSubjectsSBKPrimary = []wpmodels.CurriculumSubject{
	// Predmeti za 1 razred osnovnih škola u SBK - Bosanski NPP
	{CurriculumCode: "bos_primary_1_sbk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_1_sbk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_1_sbk", SubjectCode: "MO"},
	{CurriculumCode: "bos_primary_1_sbk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_1_sbk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_1_sbk", SubjectCode: "VJR"},
	{CurriculumCode: "bos_primary_1_sbk", SubjectCode: "TIZO"},
	// Predmeti za 2 razred osnovnih škola u SBK - Bosanski NPP
	{CurriculumCode: "bos_primary_2_sbk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_2_sbk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_2_sbk", SubjectCode: "MO"},
	{CurriculumCode: "bos_primary_2_sbk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_2_sbk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_2_sbk", SubjectCode: "VJR"},
	{CurriculumCode: "bos_primary_2_sbk", SubjectCode: "TIZO"},
	// Predmeti za 3 razred osnovnih škola u SBK - Bosanski NPP
	{CurriculumCode: "bos_primary_3_sbk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_3_sbk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_3_sbk", SubjectCode: "MO"},
	{CurriculumCode: "bos_primary_3_sbk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_3_sbk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_3_sbk", SubjectCode: "VJR"},
	{CurriculumCode: "bos_primary_3_sbk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_3_sbk", SubjectCode: "TIZO"},
	// Predmeti za 4 razred osnovnih škola u SBK - Bosanski NPP
	{CurriculumCode: "bos_primary_4_sbk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_4_sbk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_4_sbk", SubjectCode: "MO"},
	{CurriculumCode: "bos_primary_4_sbk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_4_sbk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_4_sbk", SubjectCode: "VJR"},
	{CurriculumCode: "bos_primary_4_sbk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_4_sbk", SubjectCode: "TIZO"},
	// Predmeti za 5 razred osnovnih škola u SBK - Bosanski NPP
	{CurriculumCode: "bos_primary_5_sbk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_5_sbk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_5_sbk", SubjectCode: "PRI"},
	{CurriculumCode: "bos_primary_5_sbk", SubjectCode: "DRU"},
	{CurriculumCode: "bos_primary_5_sbk", SubjectCode: "MO"},
	{CurriculumCode: "bos_primary_5_sbk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_5_sbk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_5_sbk", SubjectCode: "VJR"},
	{CurriculumCode: "bos_primary_5_sbk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_5_sbk", SubjectCode: "TIZO"},
	// Predmeti za 6 razred osnovnih škola u SBK - Bosanski NPP
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "BIO"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "NJE"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "GEO"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "HIS"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "INF"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "KZ"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "TK"},
	{CurriculumCode: "bos_primary_6_sbk", SubjectCode: "VJR"},
	// Predmeti za 7 razred osnovnih škola u SBK - Bosanski NPP
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "BIO"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "NJE"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "FIZ"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "GEO"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "HIS"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "INF"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "TK"},
	{CurriculumCode: "bos_primary_7_sbk", SubjectCode: "VJR"},
	// Predmeti za 8 razred osnovnih škola u SBK - Bosanski NPP
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "BIO"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "FIZ"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "GEO"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "HEM"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "HIS"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "INF"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "TK"},
	{CurriculumCode: "bos_primary_8_sbk", SubjectCode: "VJR"},
	// Predmeti za 9 razred osnovnih škola u SBK - Bosanski NPP
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "BIO"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "DMK"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "NJE"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "FIZ"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "GEO"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "HEM"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "HIS"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "INF"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "TK"},
	{CurriculumCode: "bos_primary_9_sbk", SubjectCode: "VJR"},
}
