package main

import (
	wpmodels "ednevnik-backend/models/workspace"
)

func strPtr(s string) *string {
	return &s
}

// CurriculumsZDK for static data
var CurriculumsZDK = []wpmodels.CurriculumCreate{
	// Bosanski NPP osnovne škole za kanton ZDK
	{CurriculumCode: "bos_primary_1_zdk", CurriculumName: "NPP za I razred osnovne škole ZDK - Bosanski jezik", ClassCode: "I", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_2_zdk", CurriculumName: "NPP za II razred osnovne škole ZDK - Bosanski jezik", ClassCode: "II", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_3_zdk", CurriculumName: "NPP za III razred osnovne škole ZDK - Bosanski jezik", ClassCode: "III", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_4_zdk", CurriculumName: "NPP za IV razred osnovne škole ZDK - Bosanski jezik", ClassCode: "IV", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_5_zdk", CurriculumName: "NPP za V razred osnovne škole ZDK - Bosanski jezik", ClassCode: "V", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_6_zdk", CurriculumName: "NPP za VI razred osnovne škole ZDK - Bosanski jezik", ClassCode: "VI", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_7_zdk", CurriculumName: "NPP za VII razred osnovne škole ZDK - Bosanski jezik", ClassCode: "VII", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_8_zdk", CurriculumName: "NPP za VIII razred osnovne škole ZDK - Bosanski jezik", ClassCode: "VIII", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "bos_primary_9_zdk", CurriculumName: "NPP za IX razred osnovne škole ZDK - Bosanski jezik", ClassCode: "IX", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: true},
	// Hrvatski NPP osnovne škole za kanton ZDK
	{CurriculumCode: "hrv_primary_1_zdk", CurriculumName: "NPP za I razred osnovne škole ZDK - Hrvatski jezik", ClassCode: "I", NPPCode: "HRV", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "hrv_primary_2_zdk", CurriculumName: "NPP za II razred osnovne škole ZDK - Hrvatski jezik", ClassCode: "II", NPPCode: "HRV", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "hrv_primary_3_zdk", CurriculumName: "NPP za III razred osnovne škole ZDK - Hrvatski jezik", ClassCode: "III", NPPCode: "HRV", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "hrv_primary_4_zdk", CurriculumName: "NPP za IV razred osnovne škole ZDK - Hrvatski jezik", ClassCode: "IV", NPPCode: "HRV", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "hrv_primary_5_zdk", CurriculumName: "NPP za V razred osnovne škole ZDK - Hrvatski jezik", ClassCode: "V", NPPCode: "HRV", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "hrv_primary_6_zdk", CurriculumName: "NPP za VI razred osnovne škole ZDK - Hrvatski jezik", ClassCode: "VI", NPPCode: "HRV", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "hrv_primary_7_zdk", CurriculumName: "NPP za VII razred osnovne škole ZDK - Hrvatski jezik", ClassCode: "VII", NPPCode: "HRV", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "hrv_primary_8_zdk", CurriculumName: "NPP za VIII razred osnovne škole ZDK - Hrvatski jezik", ClassCode: "VIII", NPPCode: "HRV", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: false},
	{CurriculumCode: "hrv_primary_9_zdk", CurriculumName: "NPP za IX razred osnovne škole ZDK - Hrvatski jezik", ClassCode: "IX", NPPCode: "HRV", CantonCode: "ZDK", TenantType: "primary", FinalCurriculum: true},
	// NPP za smjer RTIA srednje škole, bosanski NPP, ZDK
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", CurriculumName: "NPP za I razred smjera - \"Računarska tehnika i automatika\" srednje škole ZDK - Bosanski jezik", ClassCode: "I", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "secondary", CourseCode: strPtr("RTIA"), FinalCurriculum: false},
	{CurriculumCode: "bos_secondary_RTIA_2_zdk", CurriculumName: "NPP za II razred smjera - \"Računarska tehnika i automatika\" srednje škole ZDK - Bosanski jezik", ClassCode: "II", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "secondary", CourseCode: strPtr("RTIA"), FinalCurriculum: false},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", CurriculumName: "NPP za III razred smjera - \"Računarska tehnika i automatika\" srednje škole ZDK - Bosanski jezik", ClassCode: "III", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "secondary", CourseCode: strPtr("RTIA"), FinalCurriculum: false},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", CurriculumName: "NPP za IV razred smjera - \"Računarska tehnika i automatika\" srednje škole ZDK - Bosanski jezik", ClassCode: "IV", NPPCode: "BOS", CantonCode: "ZDK", TenantType: "secondary", CourseCode: strPtr("RTIA"), FinalCurriculum: true},
}

// CurriculumSubjectsZDKPrimary for static data
var CurriculumSubjectsZDKPrimary = []wpmodels.CurriculumSubject{
	// Predmeti za 1 razred osnovnih škola u ZDK - Bosanski NPP
	{CurriculumCode: "bos_primary_1_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_1_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_1_zdk", SubjectCode: "MO"},
	{CurriculumCode: "bos_primary_1_zdk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_1_zdk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_1_zdk", SubjectCode: "VJR"},
	{CurriculumCode: "bos_primary_1_zdk", SubjectCode: "TIZO"},
	// Predmeti za 2 razred osnovnih škola u ZDK - Bosanski NPP
	{CurriculumCode: "bos_primary_2_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_2_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_2_zdk", SubjectCode: "MO"},
	{CurriculumCode: "bos_primary_2_zdk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_2_zdk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_2_zdk", SubjectCode: "VJR"},
	{CurriculumCode: "bos_primary_2_zdk", SubjectCode: "TIZO"},
	// Predmeti za 3 razred osnovnih škola u ZDK - Bosanski NPP
	{CurriculumCode: "bos_primary_3_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_3_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_3_zdk", SubjectCode: "MO"},
	{CurriculumCode: "bos_primary_3_zdk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_3_zdk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_3_zdk", SubjectCode: "VJR"},
	{CurriculumCode: "bos_primary_3_zdk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_3_zdk", SubjectCode: "TIZO"},
	// Predmeti za 4 razred osnovnih škola u ZDK - Bosanski NPP
	{CurriculumCode: "bos_primary_4_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_4_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_4_zdk", SubjectCode: "MO"},
	{CurriculumCode: "bos_primary_4_zdk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_4_zdk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_4_zdk", SubjectCode: "VJR"},
	{CurriculumCode: "bos_primary_4_zdk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_4_zdk", SubjectCode: "TIZO"},
	// Predmeti za 5 razred osnovnih škola u ZDK - Bosanski NPP
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "PRI"},
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "DRU"},
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "KZ"},
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "OT"},
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "MO"},
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "VJR"},
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_5_zdk", SubjectCode: "TIZO"},
	// Predmeti za 6 razred osnovnih škola u ZDK - Bosanski NPP
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "BIO"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "NJE"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "GEO"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "HIS"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "INF"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "TK"},
	{CurriculumCode: "bos_primary_6_zdk", SubjectCode: "VJR"},
	// Predmeti za 7 razred osnovnih škola u ZDK - Bosanski NPP
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "BIO"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "NJE"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "FIZ"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "GEO"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "HIS"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "INF"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "TK"},
	{CurriculumCode: "bos_primary_7_zdk", SubjectCode: "VJR"},
	// Predmeti za 8 razred osnovnih škola u ZDK - Bosanski NPP
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "BIO"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "NJE"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "FIZ"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "GEO"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "HEM"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "HIS"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "INF"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "TK"},
	{CurriculumCode: "bos_primary_8_zdk", SubjectCode: "VJR"},
	// Predmeti za 9 razred osnovnih škola u ZDK - Bosanski NPP
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "BIO"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "NJE"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "FIZ"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "GEO"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "GOB"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "HEM"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "HIS"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "INF"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "LK"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "MK"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "TK"},
	{CurriculumCode: "bos_primary_9_zdk", SubjectCode: "VJR"},
}

// CurriculumSubjectsZDKRTIASecondary contains subjects for the RTIA secondary curriculum in ZDK
var CurriculumSubjectsZDKRTIASecondary = []wpmodels.CurriculumSubject{
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "HIS"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "INF"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "FIZ"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "HEM"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "OSELEK"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "TEHCRT"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "PRKS"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "VJR"},

	{CurriculumCode: "bos_secondary_RTIA_2_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_secondary_RTIA_2_zdk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_secondary_RTIA_2_zdk", SubjectCode: "HIS"},
	{CurriculumCode: "bos_secondary_RTIA_2_zdk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_secondary_RTIA_2_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_secondary_RTIA_2_zdk", SubjectCode: "INF"},
	{CurriculumCode: "bos_secondary_RTIA_2_zdk", SubjectCode: "FIZ"},
	{CurriculumCode: "bos_secondary_RTIA_1_zdk", SubjectCode: "OSELEK"},
	{CurriculumCode: "bos_secondary_RTIA_2_zdk", SubjectCode: "ELEKTRON"},
	{CurriculumCode: "bos_secondary_RTIA_2_zdk", SubjectCode: "PRKS"},
	{CurriculumCode: "bos_secondary_RTIA_2_zdk", SubjectCode: "VJR"},

	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "DEMOK"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "ELEKTRON"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "ELMJER"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "IDT"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "AUTO"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "RIP"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "ELENERG"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "PRKS"},
	{CurriculumCode: "bos_secondary_RTIA_3_zdk", SubjectCode: "VJR"},

	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "BJZ"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "ENG"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "SOCIO"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "TIZO"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "MM"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "ELEKTRON"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "ELMJER"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "ELKOL"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "AUTO"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "RIP"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "DRM"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "PRKS"},
	{CurriculumCode: "bos_secondary_RTIA_4_zdk", SubjectCode: "VJR"},
}
