export const pupilFields = [
  {
    label: "Ime",
    name: "name",
    placeholder: "Unesite ime",
  },
  {
    label: "Prezime",
    name: "last_name",
    placeholder: "Unesite prezime",
  },
  {
    label: "Spol",
    name: "gender",
    placeholder: "Odaberite spol",
    type: "select",
    options: [
      { value: "M", label: "Muški" },
      { value: "F", label: "Ženski" },
    ],
  },
  {
    label: "Adresa",
    name: "address",
    placeholder: "Unesite adresu",
  },
  {
    label: "Email",
    name: "email",
    placeholder: "Unesite email",
    type: "email",
  },
  {
    label: "Ime staratelja",
    name: "guardian_name",
    placeholder: "Unesite ime staratelja",
  },
  {
    label: "Broj telefona",
    name: "phone_number",
    placeholder: "Unesite broj telefona",
    type: "phone",
  },
  {
    label: "Broj telefona staratelja",
    name: "guardian_number",
    placeholder: "Unesite broj telefona staratelja",
    type: "phone",
  },
  {
    label: "Datum rođenja",
    name: "date_of_birth",
    placeholder: "Unesite datum rođenja",
    type: "date",
  },
  {
    label: "Mjesto rođenja",
    name: "place_of_birth",
    placeholder: "Unesite mjesto rođenja",
  },
  {
    label: "Vjeronauka",
    name: "religion",
    placeholder: "Odaberite vjeronauku",
    type: "select",
    options: [
      { value: "Islam", label: "Islam" },
      { value: "Catholic", label: "Katolička" },
      { value: "Orthodox", label: "Pravoslavna" },
      { value: "Jewish", label: "Jevrejska" },
      { value: "Other", label: "Ostalo" },
      { value: "NotAttendingReligion", label: "Ne pohađa" },
    ],
  },
];

export const pupilStatisticsFields = [
  {
    label: "Dijete šehida",
    name: "child_of_martyr",
    type: "checkbox",
  },
  {
    label: "Ime oca",
    name: "father_name",
    placeholder: "Unesite ime oca",
    required: false,
  },
  {
    label: "Ime majke",
    name: "mother_name",
    placeholder: "Unesite ime majke",
    required: false,
  },
  {
    label: "Roditelji RVI",
    name: "parents_rvi",
    type: "checkbox",
  },
  {
    label: "Uslovi života",
    name: "living_condition",
    type: "select",
    options: [
      { value: "both_parents", label: "Oba roditelja" },
      { value: "one_parent", label: "Jedan roditelj" },
      {
        value: "another_family_or_alone",
        label: "Druga porodica ili samostalno",
      },
      {
        value: "institution_for_children_without_parents",
        label: "Ustanova za djecu bez roditelja",
      },
    ],
    placeholder: "Odaberite uslove života",
    required: false,
  },
  {
    label: "Učenički dom",
    name: "student_dorm",
    type: "checkbox",
  },
  {
    label: "Izbjeglica",
    name: "refugee",
    type: "checkbox",
  },
  {
    label: "Povratnik iz inostranstva",
    name: "returnee_from_abroad",
    type: "checkbox",
  },
  {
    label: "Država rođenja",
    name: "country_of_birth",
    placeholder: "Unesite državu rođenja",
    required: false,
  },
  {
    label: "Država prebivališta",
    name: "country_of_living",
    placeholder: "Unesite državu prebivališta",
    required: false,
  },
  {
    label: "Državljanstvo",
    name: "citizenship",
    placeholder: "Unesite državljanstvo",
    required: false,
  },
  {
    label: "Etnička pripadnost",
    name: "ethnicity",
    placeholder: "Unesite etničku pripadnost",
    required: false,
  },
  {
    label: "Zanimanje oca",
    name: "father_occupation",
    type: "select",
    options: [
      { value: "PhD", label: "PhD" },
      { value: "MR", label: "MR" },
      { value: "VSS", label: "VSS" },
      { value: "VŠS", label: "VŠS" },
      { value: "SSS", label: "SSS" },
      { value: "KV", label: "KV" },
      { value: "OS", label: "OS" },
      { value: "NoOccupation", label: "Nema" },
    ],
    placeholder: "Odaberite zanimanje oca",
    required: false,
  },
  {
    label: "Zanimanje majke",
    name: "mother_occupation",
    type: "select",
    options: [
      { value: "PhD", label: "PhD" },
      { value: "MR", label: "MR" },
      { value: "VSS", label: "VSS" },
      { value: "VŠS", label: "VŠS" },
      { value: "SSS", label: "SSS" },
      { value: "KV", label: "KV" },
      { value: "OS", label: "OS" },
      { value: "NoOccupation", label: "Nema" },
    ],
    placeholder: "Odaberite zanimanje majke",
    required: false,
  },
  {
    label: "Nema roditelja",
    name: "has_no_parents",
    type: "checkbox",
  },
  {
    label: "Dodatne informacije",
    name: "extra_information",
    placeholder: "Unesite dodatne informacije",
    type: "text-area",
    required: false,
  },
  {
    label: "Informacije o djetetu bez roditelja",
    name: "child_alone",
    type: "text-area",
    placeholder: "Unesite dodatne informacije o djetetu bez roditelja",
    required: false,
  },
  {
    label: "Putuje u školu",
    name: "is_commuter",
    type: "checkbox",
  },
  {
    label: "Način putovanja",
    name: "commuting_type",
    type: "select",
    options: [
      { value: "Walking", label: "Pješke" },
      { value: "Bike", label: "Biciklo" },
      { value: "Car", label: "Automobil" },
      { value: "Bus", label: "Autobus" },
      { value: "Train", label: "Voz" },
      { value: "NotTraveling", label: "Ne putuje" },
    ],
    placeholder: "Odaberite način putovanja",
    required: false,
  },
  {
    label: "Udaljenost do škole",
    name: "distance_to_school_km",
    type: "select",
    options: [
      { value: "<=5km", label: "Do 5km" },
      { value: "5km - 10km", label: "5km - 10km" },
      { value: "10km - 25km", label: "10km - 25km" },
      { value: ">25km", label: "Preko 25km" },
    ],
    placeholder: "Odaberite udaljenost",
    required: false,
  },
  {
    label: "Dijete hafiz",
    name: "has_hifz",
    type: "checkbox",
  },
  {
    label: "Posebna priznanja",
    name: "special_honors",
    type: "checkbox",
  },
];
